FROM python:3.7-alpine

RUN apk add --update build-base ca-certificates make
RUN apk add \
    libjpeg \
    zlib \
    zlib-dev \
    libwebp \
    openjpeg \
    jpeg-dev \
    postgresql-libs \
    postgresql-dev \
    ncurses-dev \
    readline-dev \
    gettext \
    bash \
    gcc \
    musl-dev \
    libffi-dev \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    ttf-freefont

WORKDIR /app
COPY ./ /app
RUN pip install -r requirements.txt

EXPOSE 8000