# Generated by Django 2.0 on 2018-04-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='Region name', max_length=1000, null=True)),
                ('alias', models.CharField(blank=True, db_index=True, default=None, help_text='Region alias', max_length=1000, null=True)),
                ('oktmo_code', models.CharField(blank=True, db_index=True, default=None, help_text='Region oktmo code', max_length=20, null=True)),
                ('level', models.IntegerField(blank=True, db_index=True, default=None, help_text='Region level', null=True)),
                ('parent_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.Region')),
            ],
        ),
    ]
