# Generated by Django 2.0 on 2018-04-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.NullBooleanField(db_index=True, default=None, help_text='Region visible'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent_region',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.Region'),
        ),
    ]
