# Generated by Django 2.0 on 2018-04-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0005_mvc_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvc',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='mvc',
            name='alias',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='MVC alias', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='offence',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Participant offences', max_length=1000, null=True),
        ),
    ]
