# Generated by Django 2.0 on 2018-04-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0006_auto_20180414_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='nearby',
            field=models.ManyToManyField(db_index=True, help_text='Nearby objects', to='dtpmapapp.Nearby'),
        ),
        migrations.AddField(
            model_name='mvc',
            name='scheme',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='MVC scheme number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='car',
            field=models.ForeignKey(blank=True, default=None, help_text='Car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.Car'),
        ),
        migrations.AddField(
            model_name='participant',
            name='mvc',
            field=models.ForeignKey(blank=True, default=None, help_text='MVC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.MVC'),
        ),
    ]
