# Generated by Django 2.0 on 2018-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0007_auto_20180414_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='participants',
            field=models.IntegerField(blank=True, db_index=True, default=None, help_text='MVC participants count', null=True),
        ),
    ]
