# Generated by Django 2.0 on 2018-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0009_remove_car_manufacture_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacture_year',
            field=models.IntegerField(blank=True, db_index=True, default=None, help_text='Car manufacture year', null=True),
        ),
    ]
