# Generated by Django 2.0 on 2018-04-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0010_car_manufacture_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='car',
            field=models.ForeignKey(blank=True, default=None, help_text='Car', null=True, on_delete=django.db.models.deletion.CASCADE, to='dtpmapapp.Car'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mvc',
            field=models.ForeignKey(blank=True, default=None, help_text='MVC', null=True, on_delete=django.db.models.deletion.CASCADE, to='dtpmapapp.MVC'),
        ),
    ]
