# Generated by Django 2.0 on 2018-04-15 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0011_auto_20180415_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='source_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='Source data', null=True),
        ),
    ]
