# Generated by Django 2.0.4 on 2018-05-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0012_mvc_source_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='Street name', max_length=1000, null=True)),
                ('region', models.ForeignKey(blank=True, default=None, help_text='Area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.Region')),
            ],
        ),
        migrations.AddField(
            model_name='mvc',
            name='street',
            field=models.ForeignKey(blank=True, default=None, help_text='MVC Street', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtpmapapp.Street'),
        ),
    ]
