# Generated by Django 2.0.5 on 2018-05-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0015_auto_20180502_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='geo_updated',
            field=models.BooleanField(default=False, help_text='Geo updated'),
        ),
    ]
