# Generated by Django 2.0.5 on 2018-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0016_mvc_geo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, default=None, help_text='Region longitude', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, default=None, help_text='Region longitude', null=True),
        ),
    ]
