# Generated by Django 2.0.5 on 2018-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0017_auto_20180531_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
