# Generated by Django 2.1 on 2019-01-28 12:02

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0020_updatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Source data')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, help_text='Source data update date')),
            ],
        ),
        migrations.RemoveField(
            model_name='updatelog',
            name='area',
        ),
        migrations.DeleteModel(
            name='UpdateLog',
        ),
    ]
