# Generated by Django 2.1.5 on 2019-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0021_auto_20190209_1540'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mvc',
            index=models.Index(fields=['longitude'], name='dtpmapapp_m_longitu_d1b061_idx'),
        ),
        migrations.AddIndex(
            model_name='mvc',
            index=models.Index(fields=['latitude'], name='dtpmapapp_m_latitud_c37c51_idx'),
        ),
    ]
