# Generated by Django 2.1 on 2019-01-28 12:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0021_auto_20190128_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Source data'),
        ),
    ]
