# Generated by Django 2.1 on 2019-01-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0022_auto_20190128_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvc',
            name='source_data',
        ),
        migrations.AddField(
            model_name='sourcedata',
            name='mvc',
            field=models.ForeignKey(default=0, help_text='Source data mvc', on_delete=django.db.models.deletion.CASCADE, to='dtpmapapp.MVC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mvc',
            name='geo_updated',
            field=models.BooleanField(default=None, help_text='Geo updated'),
        ),
    ]
