# Generated by Django 2.1.5 on 2019-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0022_auto_20190209_1542'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mvc',
            name='dtpmapapp_m_id_0e0677_idx',
        ),
        migrations.RemoveIndex(
            model_name='mvc',
            name='dtpmapapp_m_longitu_d1b061_idx',
        ),
        migrations.RemoveIndex(
            model_name='mvc',
            name='dtpmapapp_m_latitud_c37c51_idx',
        ),
        migrations.RemoveField(
            model_name='mvc',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mvc',
            name='longitude',
        ),
        migrations.AddField(
            model_name='mvc',
            name='lat',
            field=models.FloatField(blank=True, default=None, help_text='MVC longitude', null=True),
        ),
        migrations.AddField(
            model_name='mvc',
            name='lng',
            field=models.FloatField(blank=True, default=None, help_text='MVC longitude', null=True),
        ),
        migrations.AddIndex(
            model_name='mvc',
            index=models.Index(fields=['id', 'lng', 'lat'], name='dtpmapapp_m_id_5e6679_idx'),
        ),
        migrations.AddIndex(
            model_name='mvc',
            index=models.Index(fields=['lng'], name='dtpmapapp_m_lng_1eb6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='mvc',
            index=models.Index(fields=['lat'], name='dtpmapapp_m_lat_5cd9c8_idx'),
        ),
    ]
