# Generated by Django 2.1.5 on 2019-02-13 04:25

import django.contrib.postgres.fields
from django.db import migrations, models, transaction
import ujson


def forwards_func(apps, schema_editor):
    with transaction.atomic():
        MVC = apps.get_model("dtpmapapp", "MVC")
        db_alias = schema_editor.connection.alias
        mvcs = MVC.objects.using(db_alias).all()
        for mvc in mvcs:
            mvc.new_conditions = list(mvc.conditions)
            mvc.save(update_fields=["new_conditions"])


def reverse_func(apps, schema_editor):
    with transaction.atomic():
        MVC = apps.get_model("dtpmapapp", "MVC")
        db_alias = schema_editor.connection.alias
        mvcs = MVC.objects.using(db_alias).all()
        for mvc in mvcs:
            mvc.conditions = ujson.dumps(mvc.new_conditions)
            mvc.save(update_fields=["new_conditions"])


class Migration(migrations.Migration):

    dependencies = [("dtpmapapp", "0023_auto_20190209_1645")]

    operations = [
        migrations.AddField(
            model_name="mvc",
            name="new_conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                default=None,
                help_text="MVC conditions",
                null=True,
                size=None,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
