# Generated by Django 2.1 on 2019-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0023_auto_20190128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
