# Generated by Django 2.1.5 on 2019-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0024_auto_20190128_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvc',
            name='geo_updated',
            field=models.BooleanField(default=None, help_text='Geo updated', null=True),
        ),
    ]
