# Generated by Django 2.1.5 on 2019-02-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0024_mvc_new_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvc',
            name='conditions',
        ),
    ]
