# Generated by Django 2.1.5 on 2019-02-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtpmapapp', '0025_remove_mvc_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvc',
            old_name='new_conditions',
            new_name='conditions',
        ),
    ]
